version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "123456a@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - my_network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this points to the Dockerfile for your ASP.NET app
    container_name: blazorapp
    ports:
      - "8080:80"   # Map port 80 in the container to port 8080 on the host
    networks:
      - my_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDatabaseName;User Id=sa;Password=123456a@
      # Replace YourDatabaseName with the actual database name in SQL Server

networks:
  my_network:
    driver: bridge
